#!/usr/bin/php
<?php

// init vars
$output = array();
$return = 0;
$exitStatus = 0;
$lintErrors = array();

// any commits?
exec('git rev-parse --verify HEAD 2> /dev/null', $output, $return);

// compare against head or nothing
$against = $return == 0 ? 'HEAD' : '4b825dc642cb6eb9a060e54bf8d69288fbee4904';

// grab files that will be commited
exec("git diff-index --cached --name-only {$against}", $output);

// loop files
foreach($output as $file) 
{
	// ignore non-php files
	if(!preg_match('/\.php$/', $file)) continue;

	// init var
	$lintOutput = array();
	exec("php -lf " . escapeshellarg($file), $lintOutput, $return);
	
	// no error found, so go to next file
	if($return == 0) continue;
	
	// join errors
	$lintErrors = array_merge($lintErrors, $lintOutput);
	
	// set status
	$exitStatus = 1;
}

// errors?
if($exitStatus == 1)
{
	echo 'PHP Lint errors:';
	echo implode("\n", $lintErrors);
}

exit($exitStatus);